import "server-only";
import { randomUUID } from "node:crypto";
import { storage } from "./storage";

/**
 * File uploads — checkpoint attachments (loading photographs, permits, PODs,
 * survey reports) and quote-request attachments (drawings, packing lists, SDS,
 * photos).
 *
 * This module owns validation and key generation. Where the bytes actually live
 * is the storage driver's business: local disk in development, a private
 * Supabase Storage bucket in production. See `lib/storage/`.
 *
 * Keys are `<scope>/<uuid>.<ext>`. The scope is the shipment id for checkpoint
 * attachments and `quote-<quoteRequestId>` for quote attachments, so the two
 * never share a directory and a file route can tell them apart by the record
 * that references it.
 *
 * The default allowlist and size limit are the checkpoint ones; `storeUpload`
 * takes an `options` argument so the quote form can widen them without the
 * checkpoint path changing.
 *
 * Attachments are never served from `public/`, for two reasons. Next resolves
 * `public/` when the server starts, so a file written at runtime is not served
 * until a restart; and anything under `public/` is readable by whoever holds
 * the URL, which would make the internal-only flag on an attachment cosmetic.
 * `/api/files/[...path]` enforces it instead.
 */

/** Attachments are served from here; what follows is the storage key. */
export const FILE_ROUTE_PREFIX = "/api/files/";

export const MAX_UPLOAD_BYTES = 10 * 1024 * 1024; // 10 MB

/**
 * Deliberately narrow. Photographs and documents are what this is for. SVG is
 * excluded on purpose — it is a script-carrying format and we serve these back
 * from our own origin.
 */
export const ALLOWED_MIME_TYPES: Record<string, string> = {
  "image/jpeg": ".jpg",
  "image/png": ".png",
  "image/webp": ".webp",
  "image/heic": ".heic",
  "application/pdf": ".pdf",
};

/**
 * Quote attachments additionally accept spreadsheets and Word documents,
 * because packing lists and technical specifications usually arrive as one.
 * Still no SVG, and no macro-enabled Office formats (.xlsm, .docm).
 */
export const QUOTE_ALLOWED_MIME_TYPES: Record<string, string> = {
  ...ALLOWED_MIME_TYPES,
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": ".xlsx",
  "application/vnd.ms-excel": ".xls",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document": ".docx",
};

/** Per file, on the public quote form. */
export const MAX_QUOTE_ATTACHMENT_BYTES = 20 * 1024 * 1024; // 20 MB
/** Across the whole submission — the deck's "max 20 MB". */
export const MAX_QUOTE_ATTACHMENTS_TOTAL_BYTES = 20 * 1024 * 1024; // 20 MB

export interface StoreUploadOptions {
  /** MIME type → extension. Defaults to ALLOWED_MIME_TYPES. */
  allowed?: Record<string, string>;
  /** Defaults to MAX_UPLOAD_BYTES. */
  maxBytes?: number;
}

/** "JPEG, PNG, WebP, HEIC, PDF, XLSX" — for error messages and the accept hint. */
export function describeAllowedTypes(allowed: Record<string, string>): string {
  return Object.values(allowed)
    .map((ext) => ext.replace(/^\./, "").toUpperCase())
    .map((ext) => (ext === "JPG" ? "JPEG" : ext === "WEBP" ? "WebP" : ext))
    .join(", ");
}

export interface StoredFile {
  fileName: string;
  /** Public URL, e.g. `/api/files/<shipmentId>/<uuid>.png` or `/api/files/quote-<id>/<uuid>.pdf`. */
  storagePath: string;
  mimeType: string;
  sizeBytes: number;
}

export class UploadError extends Error {}

/** Strips any path component a client may have put in the filename. */
function safeDisplayName(name: string): string {
  const parts = name.split(/[/\\]/);
  const base = (parts[parts.length - 1] ?? "").replace(/[^\w.\- ]+/g, "_").trim();
  return (base || "attachment").slice(0, 120);
}

/**
 * Turns a public URL back into a storage key, refusing anything that tries to
 * escape the store. Returns null rather than throwing, so callers can treat a
 * malformed value as "not found".
 */
export function storageKeyFor(storagePath: string): string | null {
  if (!storagePath.startsWith(FILE_ROUTE_PREFIX)) return null;

  const key = storagePath.slice(FILE_ROUTE_PREFIX.length);
  if (!key || key.includes("\0")) return null;

  // Keys are generated by this module and always `<scope>/<uuid>.<ext>`, where
  // the scope is a shipment id or `quote-<id>`. Anything else is rejected
  // outright, which closes traversal for every driver at once rather than
  // relying on each to defend itself.
  if (!/^[\w-]{1,64}\/[0-9a-f-]{36}\.[a-z0-9]{2,5}$/i.test(key)) return null;
  return key;
}

/**
 * Checks a file against the allowlist and size limit without storing it. The
 * quote form uses this to reject a bad batch before it creates any rows.
 */
export function validateUpload(file: File, options: StoreUploadOptions = {}): void {
  const allowed = options.allowed ?? ALLOWED_MIME_TYPES;
  const maxBytes = options.maxBytes ?? MAX_UPLOAD_BYTES;

  if (file.size === 0) throw new UploadError("That file is empty.");
  if (file.size > maxBytes) {
    throw new UploadError(
      `That file is ${(file.size / 1024 / 1024).toFixed(1)} MB. The limit is ${maxBytes / 1024 / 1024} MB.`,
    );
  }

  if (!allowed[file.type]) {
    throw new UploadError(
      allowed === ALLOWED_MIME_TYPES
        ? "Only JPEG, PNG, WebP and HEIC images and PDF documents can be attached."
        : `Only these file types can be attached: ${describeAllowedTypes(allowed)}.`,
    );
  }
}

/**
 * `scopeId` is the shipment id for checkpoint attachments, or `quote-<id>` for
 * quote attachments. It comes from our own database, but it is still used to
 * build a key, so it is constrained rather than trusted.
 */
export async function storeUpload(
  file: File,
  scopeId: string,
  options: StoreUploadOptions = {},
): Promise<StoredFile> {
  validateUpload(file, options);
  const extension = (options.allowed ?? ALLOWED_MIME_TYPES)[file.type]!;

  if (!/^[\w-]{1,64}$/.test(scopeId)) throw new UploadError("Invalid shipment reference.");

  // The stored name is generated, never taken from the upload, so a crafted
  // filename cannot escape the directory or overwrite an existing object.
  const key = `${scopeId}/${randomUUID()}${extension}`;

  try {
    await storage().put(key, Buffer.from(await file.arrayBuffer()), file.type);
  } catch (error) {
    console.error("[uploads] store failed", error);
    throw new UploadError("The file could not be saved. Please try again.");
  }

  return {
    fileName: safeDisplayName(file.name),
    storagePath: `${FILE_ROUTE_PREFIX}${key}`,
    mimeType: file.type,
    sizeBytes: file.size,
  };
}

export async function readUpload(storagePath: string) {
  const key = storageKeyFor(storagePath);
  if (!key) return null;
  return storage().get(key);
}

export async function removeUpload(storagePath: string): Promise<void> {
  const key = storageKeyFor(storagePath);
  if (!key) return;
  await storage().remove(key);
}
